"""adicionando colunas das tabelas de datas de contrato e processos administrativos

Revision ID: 6ec17f338c81
Revises: 0d4effe84c8a
Create Date: 2025-03-04 18:08:20.165281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ec17f338c81'
down_revision: Union[str, None] = '0d4effe84c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrative_processes', sa.Column('n_do_processo_spu', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('administrative_processes', sa.Column('modalidade_de_licitacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('administrative_processes', sa.Column('justificativa', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('administrative_processes', sa.Column('status_do_instrumento', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('administrative_processes', sa.Column('situacao_fisica', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('administrative_processes_contract_id_fkey', 'administrative_processes', type_='foreignkey')
    op.create_foreign_key(None, 'administrative_processes', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.add_column('contract_dates', sa.Column('data_de_assinatura', sa.DateTime(), nullable=True))
    op.add_column('contract_dates', sa.Column('data_de_termino_original', sa.DateTime(), nullable=True))
    op.add_column('contract_dates', sa.Column('data_de_termino_apos_aditivo', sa.DateTime(), nullable=True))
    op.add_column('contract_dates', sa.Column('data_de_rescisao', sa.DateTime(), nullable=True))
    op.add_column('contract_dates', sa.Column('data_publicacao_no_doe', sa.DateTime(), nullable=True))
    op.drop_constraint('contract_dates_contract_id_fkey', 'contract_dates', type_='foreignkey')
    op.create_foreign_key(None, 'contract_dates', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_dates', type_='foreignkey')
    op.create_foreign_key('contract_dates_contract_id_fkey', 'contract_dates', 'contracts', ['contract_id'], ['id'])
    op.drop_column('contract_dates', 'data_publicacao_no_doe')
    op.drop_column('contract_dates', 'data_de_rescisao')
    op.drop_column('contract_dates', 'data_de_termino_apos_aditivo')
    op.drop_column('contract_dates', 'data_de_termino_original')
    op.drop_column('contract_dates', 'data_de_assinatura')
    op.drop_constraint(None, 'administrative_processes', type_='foreignkey')
    op.create_foreign_key('administrative_processes_contract_id_fkey', 'administrative_processes', 'contracts', ['contract_id'], ['id'])
    op.drop_column('administrative_processes', 'situacao_fisica')
    op.drop_column('administrative_processes', 'status_do_instrumento')
    op.drop_column('administrative_processes', 'justificativa')
    op.drop_column('administrative_processes', 'modalidade_de_licitacao')
    op.drop_column('administrative_processes', 'n_do_processo_spu')
    # ### end Alembic commands ###
