"""tornando alguns campos de agreements opcionais

Revision ID: 6f30c9e0a5de
Revises: e0d086101f57
Create Date: 2025-03-07 18:27:32.107285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f30c9e0a5de'
down_revision: Union[str, None] = 'e0d086101f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreements', 'codigo_plano_trabalho',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agreements', 'objeto',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreements', 'objeto',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agreements', 'codigo_plano_trabalho',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
