"""Aceitando valores nulos nos campos de AgreementValues

Revision ID: 79a896c147ec
Revises: a4f3b03900ed
Create Date: 2025-03-07 19:08:20.212940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a896c147ec'
down_revision: Union[str, None] = 'a4f3b03900ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement_values', sa.Column('valor_pago', sa.Float(), nullable=True))
    op.alter_column('agreement_values', 'valor_inicial_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agreement_values', 'valor_inicial_repasse_concedente',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agreement_values', 'valor_inicial_contrapartida_convenente',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agreement_values', 'valor_atualizado_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement_values', 'valor_atualizado_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agreement_values', 'valor_inicial_contrapartida_convenente',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agreement_values', 'valor_inicial_repasse_concedente',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agreement_values', 'valor_inicial_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('agreement_values', 'valor_pago')
    # ### end Alembic commands ###
