"""tornando alguns campos de agreements opcionais

Revision ID: 87c144a283df
Revises: 6f30c9e0a5de
Create Date: 2025-03-07 18:43:46.154928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c144a283df'
down_revision: Union[str, None] = '6f30c9e0a5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreements', 'concedente',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agreements', 'convenente',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreements', 'convenente',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agreements', 'concedente',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
