"""tornando alguns campos de contrato opcionais

Revision ID: 8f2cfc417651
Revises: f553d8ce396f
Create Date: 2025-03-04 19:28:36.932893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2cfc417651'
down_revision: Union[str, None] = 'f553d8ce396f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'cpf_cnpj',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contracts', 'contratado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'contratado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contracts', 'cpf_cnpj',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
