"""aplicando valores default para AgreementValues

Revision ID: a4f3b03900ed
Revises: e0d086101f57
Create Date: 2025-03-07 19:01:00.254025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f3b03900ed'
down_revision: Union[str, None] = 'e0d086101f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreement_values', 'valor_pago')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement_values', sa.Column('valor_pago', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
