"""tornando alguns campos de contrato opcionais

Revision ID: ca41cb2d03ed
Revises: e3eb5feef018
Create Date: 2025-03-04 19:13:31.886391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca41cb2d03ed'
down_revision: Union[str, None] = 'e3eb5feef018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'contratante',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'contratante',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
