"""Adicionando tabelas de contratos e valores de contratos

Revision ID: d3f74f4a08e9
Revises: 13870e6ef705
Create Date: 2025-03-02 16:13:50.534509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3f74f4a08e9'
down_revision: Union[str, None] = '13870e6ef705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agreement_values_agreement_id_fkey', 'agreement_values', type_='foreignkey')
    op.add_column('contract_values', sa.Column('valor_original', sa.Float(), nullable=False))
    op.add_column('contract_values', sa.Column('valor_aditivo', sa.Float(), nullable=False))
    op.add_column('contract_values', sa.Column('valor_atualizado', sa.Float(), nullable=False))
    op.add_column('contract_values', sa.Column('valor_empenhado', sa.Float(), nullable=False))
    op.add_column('contract_values', sa.Column('valor_pago', sa.Float(), nullable=False))
    op.drop_constraint('contract_values_contract_id_fkey', 'contract_values', type_='foreignkey')
    op.create_foreign_key(None, 'contract_values', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.add_column('contracts', sa.Column('numero_contrato', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contracts', sa.Column('cpf_cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contracts', sa.Column('contratante', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contracts', sa.Column('contratado', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('contracts', sa.Column('tipo_objeto', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('contracts', sa.Column('objeto', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'objeto')
    op.drop_column('contracts', 'tipo_objeto')
    op.drop_column('contracts', 'contratado')
    op.drop_column('contracts', 'contratante')
    op.drop_column('contracts', 'cpf_cnpj')
    op.drop_column('contracts', 'numero_contrato')
    op.drop_constraint(None, 'contract_values', type_='foreignkey')
    op.create_foreign_key('contract_values_contract_id_fkey', 'contract_values', 'contracts', ['contract_id'], ['id'])
    op.drop_column('contract_values', 'valor_pago')
    op.drop_column('contract_values', 'valor_empenhado')
    op.drop_column('contract_values', 'valor_atualizado')
    op.drop_column('contract_values', 'valor_aditivo')
    op.drop_column('contract_values', 'valor_original')
    op.create_foreign_key('agreement_values_agreement_id_fkey', 'agreement_values', 'agreements', ['agreement_id'], ['id'])
    # ### end Alembic commands ###
