"""mundanças nos modelos

Revision ID: e0d086101f57
Revises: 8f2cfc417651
Create Date: 2025-03-07 09:02:26.075452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0d086101f57'
down_revision: Union[str, None] = '8f2cfc417651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountability', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('accountability', sa.Column('justification', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('accountability', sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('accountability', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('accountability_agreement_id_fkey', 'accountability', type_='foreignkey')
    op.create_foreign_key(None, 'accountability', 'agreements', ['agreement_id'], ['id'], ondelete='CASCADE')
    op.add_column('agreement_dates', sa.Column('data_assinatura', sa.Date(), nullable=True))
    op.add_column('agreement_dates', sa.Column('data_termino', sa.Date(), nullable=True))
    op.add_column('agreement_dates', sa.Column('data_publi_ce', sa.Date(), nullable=True))
    op.add_column('agreement_dates', sa.Column('data_publi_doe', sa.Date(), nullable=True))
    op.drop_constraint('agreement_dates_agreement_id_fkey', 'agreement_dates', type_='foreignkey')
    op.create_foreign_key(None, 'agreement_dates', 'agreements', ['agreement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('agreement_values_agreement_id_fkey', 'agreement_values', type_='foreignkey')
    op.create_foreign_key(None, 'agreement_values', 'agreements', ['agreement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agreement_values', type_='foreignkey')
    op.create_foreign_key('agreement_values_agreement_id_fkey', 'agreement_values', 'agreements', ['agreement_id'], ['id'])
    op.drop_constraint(None, 'agreement_dates', type_='foreignkey')
    op.create_foreign_key('agreement_dates_agreement_id_fkey', 'agreement_dates', 'agreements', ['agreement_id'], ['id'])
    op.drop_column('agreement_dates', 'data_publi_doe')
    op.drop_column('agreement_dates', 'data_publi_ce')
    op.drop_column('agreement_dates', 'data_termino')
    op.drop_column('agreement_dates', 'data_assinatura')
    op.drop_constraint(None, 'accountability', type_='foreignkey')
    op.create_foreign_key('accountability_agreement_id_fkey', 'accountability', 'agreements', ['agreement_id'], ['id'])
    op.drop_column('accountability', 'notes')
    op.drop_column('accountability', 'report_type')
    op.drop_column('accountability', 'justification')
    op.drop_column('accountability', 'status')
    # ### end Alembic commands ###
