"""tornando alguns campos de contrato opcionais

Revision ID: e3eb5feef018
Revises: 6ec17f338c81
Create Date: 2025-03-04 19:11:06.591373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3eb5feef018'
down_revision: Union[str, None] = '6ec17f338c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'numero_contrato',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contracts', 'objeto',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'objeto',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contracts', 'numero_contrato',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
