"""tornando campos de processos administrativos opcionais

Revision ID: f553d8ce396f
Revises: ca41cb2d03ed
Create Date: 2025-03-04 19:16:41.315630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f553d8ce396f'
down_revision: Union[str, None] = 'ca41cb2d03ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrative_processes', 'n_do_processo_spu',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('administrative_processes', 'modalidade_de_licitacao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('administrative_processes', 'justificativa',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('administrative_processes', 'status_do_instrumento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('administrative_processes', 'situacao_fisica',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrative_processes', 'situacao_fisica',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('administrative_processes', 'status_do_instrumento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('administrative_processes', 'justificativa',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('administrative_processes', 'modalidade_de_licitacao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('administrative_processes', 'n_do_processo_spu',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
